### PR TITLE
move refill to interupt - avoids needing FASTLED_ESP32_FLASH_LOCK

### PR DESCRIPTION
**Pull request by simap**
Originally the code was working well as long as I had
FASTLED_ESP32_FLASH_LOCK set

Both bits of code are in IRAM, but for some reason, the rmt was
starving unless FASTLED_ESP32_FLASH_LOCK was set and glitches occurred.

I suspect it has something to do with the handoff between the interrupt
and the main showPixels code. Perhaps some bit of code in the rtos or
some other task gets scheduled that isn't purely in IRAM, and thus gets
blocked during flash ops.

With this change, the refills happen in the interrupt and I don't appear
to need FASTLED_ESP32_FLASH_LOCK set anymore.

Also I changed the handoff flags to volatile since they cross interrupt
/ main code boundaries.

TODO might be able to refactor away gRefillChannel since its all done
inside the interrupt now.

### CODE REVIEW

**Comment by samguyer** [comment]
@simap Hi! Thanks for the patch. My branch is currently broken, but I'm getting ready to push something a lot better. Hang in there!

**Comment by simap** [comment]
Cool, I'll keep an eye peeled, and happy to help test. Thanks!
Is this PR obsoleted by new code? Should I close it?

**Comment by samguyer** [comment]
@simap It's a good question. The original version of the RMT driver (and the one in the FastLED release) has the fill routine called inside the interrupt handler. But I was concerned that we were spending too much time in there, so I tried moving it out and using a semaphore to trigger the fill routine in the regular code. The only major issue I found is that the latency of the semaphore is pretty high.

BUT you are pointing out a potentially more serious problem with this strategy, which is that during a flash memory operation, all code that is not in IRAM and not part of an interrupt handler is disabled. Here's the relevant documentation from Espressif, in case you were wondering: "To avoid reading flash cache accidentally, when one CPU initiates a flash write or erase operation, the other CPU is put into a blocked state, and all non-IRAM-safe interrupts are disabled on both CPUs until the flash operation completes."

**Comment by simap** [comment]
Yeah, I'd found that scouring the internet for that info and found your posts on reddit and the esp32 forums. 

I think long interrupts could cause issues, but I think it's worth it to not glitch and haven't noticed issues. It also seems nicer than disabling flash access (which perhaps could completely stall any non IRAM'd code, or at leas anything that needs to read data like a web server) and subjectively seems to run smoother, though I haven't tested it extensively or with any real instrumentation. There's a lot of wifi and flash access going on in my app, and I've moved most of that to CPU 0.

The combo of ws2812 and their ~5us latch time and the tiny rmt buffers seems to create a very volatile mix that is very sensitive to being delayed.

In my case running it in the interrupt hasn't been an issue, though I'm only driving one rmt controller worth of data at a time. In this case the cpu isn't doing much of anything else, it would just be spinlocking the main thread waiting for the mutex. I'd hope that if something more critical needed the cpu it would be using a higher priority interrupt, though it seems like [nested interrupts might not be enabled](https://www.esp32.com/viewtopic.php?t=5052). 

I see that `showPixels`, `fillNext`, and `interruptHandler` are all in IRAM, but perhaps something else is not. Maybe some of the rtos handoff code, or some other background task that isn't in IRAM gets run (and stalls) when the rtos switches from the interrupt handler before the code in `showPixels` continues running. Clearly something is stalling when I don't set FASTLED_ESP32_FLASH_LOCK and it isn't within those 3 functions.

I think once the mutex is given inside the interrupt, the rtos is free to schedule the next highest task, which may not always be the task that is running `showPixels`. If it was something else (maybe a timer task or some async network call) but some code within that higher priority task wasn't fully in IRAM, it could get blocked during a flash read (from itself or another core) and delay the code in `showPixels` long enough to glitch ws2812s.

**Comment by samguyer** [comment]
I think your assessment is spot on. My plan is to keep the fill work in the interrupt handler, but work to get it as fast as possible (as Mark Kriegsman says, it is called FASTled after all! ;-)

Your observation about the IRAM situation is also right on. We recently discovered that one of the API calls we're using is not in IRAM. It's the call that kicks off the RMT transmission, so it would stall any calls to showPixels. But I can just start the RMT myself by writing to the registers directly. 

I'm trying to get all of this done soon, so look out for a new checkin!

**Comment by samguyer** [comment]
Hello! I believe we have addressed all of these issues in the current head, so I'm going to close this PR. But please reopen it or submit a new issue if you think there is still a problem.

**Pull request closed without merging**
